server.port=8080

# Upstash Redis Config
spring.data.redis.host=trusty-hippo-164660.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAoM0AAIgcDI3NmE1YzA4MDViMzQ0ODI2OGU3MDI3ODJhYTIyOWUwNQ
spring.data.redis.ssl.enabled=true

# Local MongoDB Config
spring.data.mongodb.database=thread_co_db
spring.data.mongodb.uri=mongodb://localhost:27017/thread_co_db

# Disable RabbitMQ auto-startup listener if host is not configured
spring.rabbitmq.listener.simple.auto-startup=false