apiVersion: v1
kind: ConfigMap
metadata:
  name: thread-co-config
data:
  SPRING_DATA_REDIS_HOST: "trusty-hippo-164660.upstash.io"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_MONGODB_URI: "mongodb://localhost:27017/thread_co_db"
